DECLARE
v_count NUMBER;
BEGIN
SELECT COUNT(*)
INTO v_count
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'NBPT6'
  AND TABLE_NAME = 'USER_PROFILES'
  AND COLUMN_NAME = 'PROFILE_IMAGE';

IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE NBPT6.USER_PROFILES ADD PROFILE_IMAGE BLOB';
END IF;
END;
/

DECLARE
v_count NUMBER;
BEGIN
SELECT COUNT(*)
INTO v_count
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'NBPT6'
  AND TABLE_NAME = 'USER_PROFILES'
  AND COLUMN_NAME = 'PROFILE_IMAGE_CONTENT_TYPE';

IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE NBPT6.USER_PROFILES ADD PROFILE_IMAGE_CONTENT_TYPE VARCHAR2(100)';
END IF;
END;
/

DECLARE
v_count NUMBER;
BEGIN
SELECT COUNT(*)
INTO v_count
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'NBPT6'
  AND TABLE_NAME = 'USER_PROFILES'
  AND COLUMN_NAME = 'PROFILE_IMAGE_FILE_NAME';

IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE NBPT6.USER_PROFILES ADD PROFILE_IMAGE_FILE_NAME VARCHAR2(255)';
END IF;
END;
/