DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM ALL_TABLES
    WHERE OWNER = 'NBPT6' AND TABLE_NAME = 'INVOICES';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE NBPT6.INVOICES (
                ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                PAYMENT_ID      NUMBER NOT NULL,
                BOOKING_ID      NUMBER NOT NULL,
                USER_ID         NUMBER NOT NULL,
                INVOICE_NUMBER  VARCHAR2(50) NOT NULL UNIQUE,
                ISSUED_AT       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                TOTAL_AMOUNT    NUMBER(10,2) NOT NULL,
                PDF_DATA        BLOB,
                CONSTRAINT FK_INVOICE_PAYMENT FOREIGN KEY (PAYMENT_ID) REFERENCES NBPT6.PAYMENTS(ID),
                CONSTRAINT FK_INVOICE_BOOKING FOREIGN KEY (BOOKING_ID) REFERENCES NBPT6.BOOKINGS(ID)
            )
        ';
    END IF;
END;
/
