CREATE OR REPLACE VIEW NBPT6.V_CITIES_WITH_COUNTRY AS
SELECT
    c.ID,
    c.COUNTRY_ID,
    c.NAME,
    c.POSTAL_CODE,
    c.DESCRIPTION,
    c.IMAGE_URL,
    co.NAME AS COUNTRY_NAME,
    co.CONTINENT
FROM NBPT6.CITIES c
         JOIN NBPT6.COUNTRIES co ON c.COUNTRY_ID = co.ID;