CREATE OR REPLACE VIEW NBPT6.V_CITIES_WITH_COUNTRY AS
SELECT
    c.ID,
    c.COUNTRY_ID,
    c.NAME,
    c.POSTAL_CODE,
    c.DESCRIPTION,
    c.IMAGE_URL,
    co.NAME AS COUNTRY_NAME,
    co.CONTINENT
FROM NBPT6.CITIES c
         JOIN NBPT6.COUNTRIES co ON c.COUNTRY_ID = co.ID;

CREATE OR REPLACE VIEW NBPT6.V_REVIEWS_WITH_USER AS
SELECT
    r.ID,
    r.USER_ID,
    r.ACCOMMODATION_ID,
    r.ACTIVITY_ID,
    r.RATING,
    r.NOTE,
    r.CREATED_AT,
    u.FIRST_NAME || ' ' || u.LAST_NAME AS USER_NAME,
    CASE
        WHEN a.CITY IS NOT NULL AND a.COUNTRY IS NOT NULL
            THEN a.CITY || ', ' || a.COUNTRY
        WHEN a.CITY IS NOT NULL
            THEN a.CITY
        WHEN a.COUNTRY IS NOT NULL
            THEN a.COUNTRY
        ELSE NULL
        END AS USER_LOCATION
FROM NBPT6.REVIEWS r
         JOIN NBP.NBP_USER u ON r.USER_ID = u.ID
         LEFT JOIN NBPT6.ADDRESSES a ON u.ADDRESS_ID = a.ID;

CREATE OR REPLACE VIEW NBPT6.V_USERS_WITH_ROLES AS
SELECT
    u.ID,
    u.FIRST_NAME,
    u.LAST_NAME,
    u.USERNAME,
    u.EMAIL,
    u.PASSWORD AS PASSWORD_HASH,
    u.PHONE_NUMBER AS PHONE,
    r.NAME AS ROLE
FROM NBP.NBP_USER u
         LEFT JOIN NBP.NBP_ROLE r ON u.ROLE_ID = r.ID;