-- =========================
-- COUNTRIES
-- =========================
CREATE TABLE countries (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL UNIQUE,
    code VARCHAR2(10) NOT NULL UNIQUE,
    currency VARCHAR2(50),
    language VARCHAR2(50)
);

-- =========================
-- CITIES
-- =========================
CREATE TABLE cities (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    country_id NUMBER NOT NULL,
    name VARCHAR2(100) NOT NULL,
    postal_code VARCHAR2(20),
    description VARCHAR2(500),

    CONSTRAINT fk_city_country
    FOREIGN KEY (country_id)
    REFERENCES countries(id)
);

-- =========================
-- TRIPS
-- =========================
CREATE TABLE trips (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    title VARCHAR2(255) NOT NULL,
    description VARCHAR2(500),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    budget NUMBER(10,2),
    status VARCHAR2(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_trip_user
    FOREIGN KEY (user_id)
    REFERENCES nbp.nbp_user(id)
);

-- =========================
-- TRIP_CITIES
-- =========================
CREATE TABLE trip_cities (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id NUMBER NOT NULL,
    city_id NUMBER NOT NULL,
    arrival_date DATE,
    departure_date DATE,
    notes VARCHAR2(500),

    CONSTRAINT fk_tripcity_trip
    FOREIGN KEY (trip_id)
    REFERENCES trips(id),

    CONSTRAINT fk_tripcity_city
    FOREIGN KEY (city_id)
    REFERENCES cities(id)
);

-- =========================
-- ACCOMMODATION TYPES
-- =========================
CREATE TABLE accommodation_types (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE
);

-- =========================
-- ACCOMMODATIONS
-- =========================
CREATE TABLE accommodations (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id NUMBER NOT NULL,
    accommodation_type_id NUMBER NOT NULL,
    name VARCHAR2(255) NOT NULL,
    address VARCHAR2(255),
    description VARCHAR2(500),
    price_per_night NUMBER(10,2),
    max_guests NUMBER,
    stars NUMBER,
    phone VARCHAR2(50),
    email VARCHAR2(100),

    CONSTRAINT fk_acc_city
    FOREIGN KEY (city_id)
    REFERENCES cities(id),

    CONSTRAINT fk_acc_type
    FOREIGN KEY (accommodation_type_id)
    REFERENCES accommodation_types(id)
);

-- =========================
-- BOOKINGS
-- =========================
CREATE TABLE bookings (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id NUMBER NOT NULL,
    user_id NUMBER NOT NULL,
    accommodation_id NUMBER NOT NULL,
    check_in DATE NOT NULL,
    check_out DATE NOT NULL,
    guests_count NUMBER,
    total_price NUMBER(10,2),
    booking_status VARCHAR2(50),
    booking_reference VARCHAR2(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_booking_trip
    FOREIGN KEY (trip_id)
    REFERENCES trips(id),

    CONSTRAINT fk_booking_user
    FOREIGN KEY (user_id)
    REFERENCES nbp.nbp_user(id),

    CONSTRAINT fk_booking_acc
    FOREIGN KEY (accommodation_id)
    REFERENCES accommodations(id)
);

-- =========================
-- ACTIVITY TYPES
-- =========================
CREATE TABLE activity_types (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE
);

-- =========================
-- ACTIVITIES
-- =========================
CREATE TABLE activities (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id NUMBER NOT NULL,
    city_id NUMBER NOT NULL,
    activity_type_id NUMBER NOT NULL,
    name VARCHAR2(255) NOT NULL,
    description VARCHAR2(500),
    location VARCHAR2(255),
    activity_date DATE,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    price NUMBER(10,2),

    CONSTRAINT fk_act_trip
    FOREIGN KEY (trip_id)
    REFERENCES trips(id),

    CONSTRAINT fk_act_city
    FOREIGN KEY (city_id)
    REFERENCES cities(id),

    CONSTRAINT fk_act_type
    FOREIGN KEY (activity_type_id)
    REFERENCES activity_types(id)
);

-- =========================
-- REVIEWS
-- =========================
CREATE TABLE reviews (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    accommodation_id NUMBER,
    activity_id NUMBER,
    rating NUMBER CHECK (rating BETWEEN 1 AND 5),
    note VARCHAR2(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_review_user
    FOREIGN KEY (user_id)
    REFERENCES nbp.nbp_user(id),

    CONSTRAINT fk_review_acc
    FOREIGN KEY (accommodation_id)
    REFERENCES accommodations(id),

    CONSTRAINT fk_review_act
    FOREIGN KEY (activity_id)
    REFERENCES activities(id)
);

-- =========================
-- PAYMENT METHODS
-- =========================
CREATE TABLE payment_methods (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE
);

-- =========================
-- PAYMENTS
-- =========================
CREATE TABLE payments (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id NUMBER NOT NULL,
    booking_id NUMBER,
    user_id NUMBER NOT NULL,
    payment_method_id NUMBER NOT NULL,
    amount NUMBER(10,2) NOT NULL,
    payment_date TIMESTAMP,
    payment_status VARCHAR2(50),

    CONSTRAINT fk_payment_trip
    FOREIGN KEY (trip_id)
    REFERENCES trips(id),

    CONSTRAINT fk_payment_booking
    FOREIGN KEY (booking_id)
    REFERENCES bookings(id),

    CONSTRAINT fk_payment_user
    FOREIGN KEY (user_id)
    REFERENCES nbp.nbp_user(id),

    CONSTRAINT fk_payment_method
    FOREIGN KEY (payment_method_id)
    REFERENCES payment_methods(id)
);

-- =========================
-- TRANSPORT TYPES
-- =========================
CREATE TABLE transport_types (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(50) NOT NULL UNIQUE
);

-- =========================
-- TRANSPORT
-- =========================
CREATE TABLE transport (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trip_id NUMBER NOT NULL,
    from_city_id NUMBER NOT NULL,
    to_city_id NUMBER NOT NULL,
    transport_type_id NUMBER NOT NULL,
    company_name VARCHAR2(255),
    departure_time TIMESTAMP,
    arrival_time TIMESTAMP,
    ticket_price NUMBER(10,2),
    seat_number VARCHAR2(50),
    booking_reference VARCHAR2(255),

    CONSTRAINT fk_transport_trip
    FOREIGN KEY (trip_id)
    REFERENCES trips(id),

    CONSTRAINT fk_transport_from_city
    FOREIGN KEY (from_city_id)
    REFERENCES cities(id),

    CONSTRAINT fk_transport_to_city
    FOREIGN KEY (to_city_id)
    REFERENCES cities(id),

    CONSTRAINT fk_transport_type
    FOREIGN KEY (transport_type_id)
    REFERENCES transport_types(id)
);

-- =========================
-- ADDRESSES
-- =========================
CREATE TABLE addresses (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street VARCHAR2(255) NOT NULL,
    city VARCHAR2(100) NOT NULL,
    postal_code VARCHAR2(20),
    country VARCHAR2(100) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);