-- =========================
-- REFRESH TOKENS (Private schema)
-- =========================
CREATE TABLE refresh_tokens (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    token VARCHAR2(255) NOT NULL UNIQUE,
    expiry_date TIMESTAMP NOT NULL,

    CONSTRAINT fk_refreshtoken_user
    FOREIGN KEY (user_id)
    REFERENCES nbp.nbp_user(id)
);
