-- FINAL HASH PASSWORDS FOR ALL TEAM MEMBERS
-- Azra: azra123
-- Adna: adna123
-- Nadina: nadina123
-- Amina: amina123
-- Nerma: nerma123

UPDATE NBP.NBP_USER SET PASSWORD = '$2a$10$NJduIXErK/T77KZvoYO6H.6JBOvHezbDQBFqjla2mGtMjFMyNoEoi' WHERE USERNAME = 'azunic3';
UPDATE NBP.NBP_USER SET PASSWORD = '$2a$10$.TfFATu7CQnBOtyBaFZCAe9Eo6uULWKUvmKi8NCWdpIXLfcqT7cp.' WHERE USERNAME = 'aherak2';
UPDATE NBP.NBP_USER SET PASSWORD = '$2a$10$G6fq7dJ1BkRJosxShb6LCus9zCWWTPq66QL5vKjJcn2Ax3eRfBH1i' WHERE USERNAME = 'nmiralem1';
UPDATE NBP.NBP_USER SET PASSWORD = '$2a$10$WEcM2pazM.6EVMg3LWUgme6Ozqu4QRo5VqrZGPBm4cJjsIcoPRpRi' WHERE USERNAME = 'ahromic1';
UPDATE NBP.NBP_USER SET PASSWORD = '$2a$10$vhoidkvBrfIcWTtFfxb1UOL1aeoysTrfyubIg5l/fTlhcGymiGuUy' WHERE USERNAME = 'nkadric1';

COMMIT;
