-- BOOKINGS
ALTER TABLE NBPT6.BOOKINGS
ADD PREMIUM_FLAG NUMBER(1);

-- ACCOMMODATIONS
ALTER TABLE NBPT6.ACCOMMODATIONS
ADD PREMIUM_FLAG NUMBER(1);

-- ACTIVITIES (pazi typo!)
ALTER TABLE NBPT6.ACTIVITIES
ADD PREMIUM_FLAG NUMBER(1);

-- TRANSPORT
ALTER TABLE NBPT6.TRANSPORT
ADD PREMIUM_FLAG NUMBER(1);

-- TRIPS
ALTER TABLE NBPT6.TRIPS
ADD PREMIUM_FLAG NUMBER(1);

-- PAYMENTS
ALTER TABLE NBPT6.PAYMENTS
ADD DISCOUNT NUMBER(5,2) DEFAULT 0;